=== chaosunabc/bana/common-util/common-util/src/main/resources/office/excelConfig.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:element name="excel">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="sheet" type="sheet" minOccurs="1" maxOccurs="10"></xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string"/>
			<xs:attribute name="type" type="excelType" use="required"/>
			<xs:attribute name="style" type="xs:string"/>
		</xs:complexType>
		<xs:key name="sheet_name">
	   		<xs:selector xpath=".//sheet"/>
	   		<xs:field xpath="@name"/>
	  	</xs:key>
	</xs:element>
	
	<!-- 定义excel的Type类型枚举 -->
	<xs:simpleType name="excelType">
	  <xs:restriction base="xs:string">
	    <xs:enumeration value="xls"/>
	    <xs:enumeration value="xlsx"/>
	  </xs:restriction>
	</xs:simpleType>
	<!-- 定义row的Type类型枚举 -->
	<xs:simpleType name="rowType">
	  <xs:restriction base="xs:string">
	    <xs:enumeration value="data"/>
	    <xs:enumeration value="title"/>
	  </xs:restriction>
	</xs:simpleType>
	<!-- 定义sheet标签的复杂标签类型 -->
	<xs:complexType name="sheet">
		<xs:sequence>
			<xs:element name="row" type="row" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="style" type="xs:string"/>
		<xs:attribute name="checkTitle" type="xs:boolean" default="false"></xs:attribute>
	</xs:complexType>
	<!-- 定义row标签的复杂标签类型 -->
	<xs:complexType name="row">
		<xs:sequence>
			<xs:element name="column" type="column" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
		<xs:attribute name="type" type="rowType" use="required"/>
		<xs:attribute name="rowIndex" type="xs:integer" default="-1"/><!-- -1默认是从当前行进行继续加载 -->
		<xs:attribute name="class" type="xs:string"/><!-- -1默认是从当前行进行继续加载 -->
		<xs:attribute name="style" type="xs:string"/>
		<xs:attribute name="mutiTitle" type="xs:boolean"></xs:attribute>
	</xs:complexType>
	<!-- 定义row标签的复杂标签类型 -->
	<xs:complexType name="column">
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="colspan" default="1" type="xs:positiveInteger"/>
		<xs:attribute name="mappedBy" type="xs:string"/>
		<xs:attribute name="style" type="xs:string"/>
		<xs:attribute name="type" type="xs:string"></xs:attribute>
		<xs:attribute name="mutiMap" type="xs:string"></xs:attribute>
		<xs:attribute name="useDic" type="xs:boolean"></xs:attribute>
		<xs:attribute name="dicType" type="xs:string"></xs:attribute>
	</xs:complexType>
	
</xs:schema>

=== chaosunabc/bana/common-util-parent/common-util/src/test/resources/office/excelConfig.bak.xml
<?xml version="1.0" encoding="UTF-8" ?>
<excel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="http://www.bana.com/common-util/excelConfig.xsd" 
type="xls" name="测试名称">
	<sheet name="test1">
		
	</sheet>
	<sheet name="test1"/>
	<sheet name="代收到付进账单明细"
		class="com.jbinfo.ecms.finance.domain.report.PostBankReportDomain"
		titleRowIndex="3" columnWidth="0:14;1:14;2:11;3:17;4:12;5:18">
		<column name="序列" mappedBy="columnIndex" titleFont="fontName:宋体;fontHeightInPoints:9"
			titleStyle="border:all">
			<style style="border:all"></style>
		</column>
		<column name="部门" mappedBy="orgName" titleFont="fontName:宋体;fontHeightInPoints:9"
			titleStyle="border:all">
			<style style="border:all"></style>
		</column>
		<column name="事项" mappedBy="moneyType" useDic="true"
			dicType="postal_bank_money_type" titleFont="fontName:宋体;fontHeightInPoints:9"
			titleStyle="border:all">
			<style style="border:all"></style>
		</column>
		<column name="金额" mappedBy="itemMoney" type="NUMERIC"
			data-params="formulaType:SUM,from:4" titleFont="fontName:宋体;fontHeightInPoints:9"
			titleStyle="border:all">
			<style style="border:all"></style>
		</column>
		<column name="资金性质" default="速递" titleFont="fontName:宋体;fontHeightInPoints:9"
			titleStyle="border:all">
			<style style="border:all"></style>
		</column>
		<column name="备注" mappedBy="remark" titleFont="fontName:宋体;fontHeightInPoints:9"
			titleStyle="border:all">
			<style style="border:all"></style>
		</column>
	</sheet>
	<sheet name="代收到付汇总表">
		<!-- 增加行合计 -->
		<column name="合计" type="FORMULA" data-params="formulaType:SUM,from:1">
			<style style="boder:all" />
		</column>
	</sheet>
</excel>

=== chaosunabc/bana/common-util/common-util/src/test/resources/office/excelStudentAchievement.xml
<?xml version="1.0" encoding="UTF-8" ?>
<excel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="http://www.bana.com/common-util/excelConfig.xsd" 
type="xls" name="学生成绩单" style="border:all;fontName:微软雅黑;">
	<sheet name="学生成绩单" checkTitle="true">
		<row type="title" rowIndex="-1" style="fontWeight:bold;fontHeightInPoints:14;alignment:ALIGN_CENTER;"><!-- 列按照顺序进行排列 -->
			<column name="学生成绩单" colspan="10"/>
		</row>
		<row type="title" mutiTitle="true" rowIndex="-1" style="fontHeightInPoints:10;"><!-- 列按照顺序进行排列 -->
			<column name="序号" />
			<column name="成绩单" colspan="1"/>
			<column name="学生编号" colspan="1"/>
			<column name="学生姓名" colspan="1"/>
			<column name="班级名称" colspan="1"/>
			<column name="科目" colspan="1"/>	
			<column name="成绩" colspan="1"/>
			<column name="考试日期" colspan="1"/>	
			<column name="老师评语" colspan="1"/>	
			<column name="发布人" colspan="1"/>			
		</row>
		<row type="data" rowIndex="-1" style="fontHeightInPoints:10;" class="org.bana.common.util.office.impl.StudentScoreDto4Query">
			<column name="序号" mappedBy="@index" style="dataFormat:#"/>
			<column name="成绩单" mappedBy="title"/>
			<column name="学生编号" mappedBy="studentId" style="dataFormat:#" type="long"/>
			<column name="学生姓名" mappedBy="studentName"/>
			<column name="班级名称" mappedBy="classOrgName"/>
			<column name="科目" mappedBy="subject"/>
			<column name="成绩" mappedBy="score"/>
			<column name="考试日期" mappedBy="examinationTime"  type="date"/>
			<column name="老师评语" mappedBy="comment"/>
			<column name="发布人" mappedBy="createName"/>
		</row>
	</sheet>
</excel>

=== chaosunabc/bana/common-util-parent/common-util-file/src/test/resources/office/excelConfigStudentScore.xml
<?xml version="1.0" encoding="UTF-8" ?>
<excel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="http://www.bana.com/common-util/excelConfig.xsd" 
type="xls" name="学生成绩单" style="border:all;fontName:微软雅黑;">
	<sheet name="学生成绩单" checkTitle="true">
		<row type="title" rowIndex="-1" style="fontWeight:bold;fontHeightInPoints:14;alignment:ALIGN_CENTER;"><!-- 列按照顺序进行排列 -->
			<column name="学生成绩单" colspan="6"/>
		</row>
		<row type="title" rowIndex="-1" style="fontHeightInPoints:10;"><!-- 列按照顺序进行排列 -->
			<column name="班级名称" colspan="1"/>
			<column name="考试时间" colspan="1"/>	
			<column name="学生编号" colspan="1"/>
			<column name="学生姓名" colspan="1"/>
			<column name="科目" colspan="1"/>	
			<column name="成绩" colspan="1"/>
			<column name="老师评语" colspan="1"/>	
					
		</row>
		<row type="data" rowIndex="-1" style="fontHeightInPoints:10;" class="com.jbinfo.i3618.message.dto.StudentScoreDto">
			<column mappedBy="classOrgName"/>
			<column mappedBy="examinationTime"/>
			<column mappedBy="studentIdStr"/>
			<column mappedBy="studentName"/>
			<column mappedBy="subject"/>
			<column mappedBy="score"/>
			<column mappedBy="comment"/>
		</row>
	</sheet>
</excel>

=== chaosunabc/bana/common-util/common-util/src/test/resources/office/excelMutiConfig.xml
<?xml version="1.0" encoding="UTF-8" ?>
<excel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="http://www.bana.com/common-util/excelConfig.xsd" 
type="xls" name="测试名称" style="border:all;fontName:微软雅黑;">
	<sheet name="sheet1-test" checkTitle="true">
		<row type="title" rowIndex="5" style="fontWeight:bold;"><!-- 列按照顺序进行排列 -->
			<column name="系统用户统计数据" colspan="5"/>
		</row>
		<row type="title" mutiTitle="true" rowIndex="-1"><!-- 列按照顺序进行排列 -->
			<column name="序号" />
			<column name="姓名" colspan="1"/>
			<column name="性别" colspan="1" mutiMap="年龄"/>
			<column name="年龄" colspan="1"/>
			<column name="住址" colspan="1"/>
			<column name="日期" colspan="1"/>
		</row>
		<row type="data" class="org.bana.common.util.office.impl.TestData" rowIndex="-1">
			<column name="序号" mappedBy="@index"/>
			<column name="姓名" mappedBy="name"/>
			<column name="性别" mappedBy="sex" mutiMap="年龄" colspan="1"/>
			<column name="年龄" mappedBy="age" style="dataFormat:#" type="int"/>
			<column name="住址" mappedBy="address"/>
			<column name="日期" mappedBy="date" style="dataFormat:yyyy年MM月dd日 HH时mm分ss秒;" type="date"/>
		</row>
	</sheet>
</excel>

=== chaosunabc/bana/common-util-parent/common-util-file/src/test/resources/office/excelConfig.xml
<?xml version="1.0" encoding="UTF-8" ?>
<excel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.bana.com/excelConfig
	http://www.bana.com/common-util/excelConfig.xsd"
type="xls" name="测试名称" style="border:all;fontName:微软雅黑;" baseFile="/office/学生成绩单模版-科目横版-v1.1 - 副本.xls">
	<sheet name="sheet1-test">
		<row type="title" rowIndex="5" style="fontWeight:bold;"><!-- 列按照顺序进行排列 -->
			<column name="系统用户统计数据" colspan="7"/>
		</row>
		<row type="title" rowIndex="-1"><!-- 列按照顺序进行排列 -->
			<column name="序号" />
			<column name="姓名" colspan="1" style="fillForegroundColor:yellow;"/>
			<column name="性别" colspan="2"/>
			<column name="年龄" colspan="1" style="fillForegroundColor:red;"/>
			<column name="住址" colspan="1" style="fillForegroundColor:dark_blue;"/>
			<column name="日期" colspan="1"/>
		</row>
		<row type="data" class="org.bana.common.util.office.annotation.TestData" rowIndex="-1">
			<column mappedBy="@index"/>
			<column mappedBy="name"/>
			<column mappedBy="sex" colspan="2"/>
			<column mappedBy="age" style="dataFormat:#" type="int" useDic="true" dicType="postal_bank_money_type"/>
			<column mappedBy="address"/>
			<column mappedBy="date" style="dataFormat:yyyy年MM月dd日 HH时mm分ss秒;" type="date"/>
		</row>
	</sheet>
</excel>
